global_costmap:

  map_type: costmap
  track_unknown_space: true
  unknown_cost_value: 2
  obstacle_range: 1.5
  raytrace_range: 10.0
  footprint: [[0.25, 0.25],
              [-0.25, 0.25],
              [-0.25, -0.25],
              [0.25, -0.25]]
  inflation_radius: 0.32
  transform_tolerance: 0.5
  inscribed_radius: 0.3
  circumscribed_radius: 0.32

  global_frame: /map
  robot_base_frame: /base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: false

  #Investigate what this actually does
  cost_scaling_factor: 10.0
