(cl:defpackage frontier_exploration-msg
  (:use )
  (:export
   "<FRONTIER>"
   "FRONTIER"
   "<EXPLORETASKGOAL>"
   "EXPLORETASKGOAL"
   "<EXPLORETASKFEEDBACK>"
   "EXPLORETASKFEEDBACK"
   "<EXPLORETASKACTIONRESULT>"
   "EXPLORETASKACTIONRESULT"
   "<EXPLORETASKACTIONGOAL>"
   "EXPLORETASKACTIONGOAL"
   "<EXPLORETASKACTION>"
   "EXPLORETASKACTION"
   "<EXPLORETASKACTIONFEEDBACK>"
   "EXPLORETASKACTIONFEEDBACK"
   "<EXPLORETASKRESULT>"
   "EXPLORETASKRESULT"
  ))

